environment:
  matrix:
  - arch: x86
    vsver: 150
  - arch: x64
    vsver: 150
  - arch: x86
    vsver: 90
  - arch: x64
    vsver: 90
    PYTHON_ARCH: 64
    PATCH_VS2008: True
install:
- cmd: git submodule update --init --recursive
- ps: install-module pscx -scope CurrentUser
- ps: >-
    if ($env:PATCH_VS2008 -eq 'True') {
        # http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#patch-vs2008-py
        C:\Python27\python -m pip install scikit-ci-addons
        C:\Python27\python -m ci_addons appveyor/patch_vs2008
        # http://help.appveyor.com/discussions/kb/38-visual-studio-2008-64-bit-builds
        Copy-Item "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"
    }
build: off
build_script:
- ps: >-
    .\build.ps1 -arch:$env:arch -vsver:$env:vsver

test: off
test_script:
- ps: Get-ChildItem dist\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
