environment:
  matrix:
  - Architecture: x86
    Compiler: vs2019
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - Architecture: x64
    Compiler: vs2019
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - Architecture: arm64
    Compiler: vs2019
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - Architecture: x86
    Compiler: vs2008
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - Architecture: x64
    Compiler: vs2008
    PYTHON_ARCH: 64
    PATCH_VS2008: True
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

install:
- cmd: git submodule update --init --recursive
- cmd: cd libiconv
- cmd: git apply ..\libiconv.patch
- cmd: cd ..
- ps: install-module pscx -scope CurrentUser -AllowClobber
- ps: >-
    if ($env:PATCH_VS2008 -eq 'True') {
        # http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#patch-vs2008-py
        C:\Python27\python -m pip install scikit-ci-addons
        C:\Python27\python -m ci_addons appveyor/patch_vs2008
        # http://help.appveyor.com/discussions/kb/38-visual-studio-2008-64-bit-builds
        Copy-Item "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"
    }
build: off
build_script:
- ps: >-
    $x64param = if ($env:Architecture -eq 'x64') { $true } else { $false }

    $arm64param = if ($env:Architecture -eq 'arm64') { $true } else { $false }

    $vs2008param = if ($env:Compiler -eq 'vs2008') { $true } else { $false }

    .\build.ps1 -x64:$x64param -arm64:$arm64param -vs2008:$vs2008param

test: off
test_script:
- ps: Get-ChildItem dist\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
